### PR TITLE
feat: Add cli

### PR DESCRIPTION
**Pull request by timfish**
Adds a cli that can be used to add debug IDs to any directory of files.

We also run the CLI after build on our own `dist` directory so that our output files have debug IDs!

### CODE REVIEW

**Review by AbhiPrasad — APPROVED** [review]
We need to add an engines to `package.json` if we have a CLI.

I created https://github.com/getsentry/javascript-debug-ids/issues/8 to track publishing. We also should think about making this a monorepo and individually publishing stuff.

**Comment by timfish** [comment]
> We also should think about making this a monorepo and individually publishing stuff

I was hoping we could just keep a single package since there are no dependencies, there's not much code and the exports mean that the different features are quite isolated.

The only plus I can see from a monorepo is that we can have e2e tests that actually ref the package rather than a relative path, ie `../../dist/rollup.js`.

**Comment by timfish** [comment]
Adding `engines` causes the parcel tests to fail seemingly due to [this](https://github.com/parcel-bundler/parcel/issues/9616) so I'll add that in later!

**Comment by AbhiPrasad** [comment]
> I was hoping we could just keep a single package since there are no dependencies, there's not much code and the exports mean that the different features are quite isolated.

For bundler plugins we should always emit separate packages because it makes peer deps resolution easier. It also means we can individually control min node versions.

Another advantage is that download analytics becomes much more valuable, we can track specific adoption way more easily (which is important because we are trying to make the case to upstream these).

**Pull request merged**
