### PR TITLE
feat: Document native webpack support

### LINKED ISSUE #37: Debug IDs in Webpack
https://github.com/webpack/webpack

### PR DESCRIPTION
**Pull request by timfish**
Closes #37

### CODE REVIEW

**Review by AbhiPrasad — APPROVED** [review]
Nice!

**Comment by AbhiPrasad** [comment]
I just realized we need to update https://webpack.js.org/configuration/devtool/#devtool to add the debug ids option

**Comment by AbhiPrasad** [comment]
Oh wait it's documented here: https://webpack.js.org/plugins/source-map-dev-tool-plugin/#options

Should we also add it to https://webpack.js.org/configuration/devtool/#devtool?

**Comment by timfish** [comment]
Possibly, but I'm not sure of a good way to add it without making that table matrix twice as long 😂

**Pull request merged**
